Adding a page of details for every book when book's title is clicked
Borders-None/bookshop-project-2020-autumn pull request #17
Opened 2020-12-12 20:40 UTC by AhmadAlkaati

Fetching all data from online API and making an html page that has details for every book

2020-12-13 09:08 UTC, mladenuzelac approved these changes
This is nicely done. Solve conflicts and merge it with the main branch.
Pull the code from the repository and create a new branch with a name that related to the task.
I see something that will be fixed in the next PR.

2020-12-14 13:45 UTC, AhmadAlkaati commented
Hi @mladenuzelac  Thanks for reviewing my code :) 
Should I delete the current pull request and make a new one in a new branch ?

2020-12-14 13:48 UTC, mladenuzelac commented
First fix the conflicts and merge into the main branch. 
After the merge create a branch from the main branch.
Name of the branch should reflect what you are doing.

2020-12-14 13:51 UTC, josipgrgic commented on books/book.js
> +  fetch("https://bookshop-api.mirkwood.dev/books/")
getBook should call the https://bookshop-api.mirkwood.dev/books/id endpoint to get a single book and not all the books. It is not necessary to get all the books just to display info about a single book. Imagine you have 1 million books and used this approach - the user would wait for a long time to get a massive amount of data even though they don't need to.

2020-12-14 13:53 UTC, josipgrgic commented on books/book.js
> +          let title = ` <h2 class = 'title' > ${book.title} </h2>`;
Create a separate function in which you will handle the display of the book

2020-12-14 13:54 UTC, josipgrgic requested changes
Please fix the thing I pointed out and then I will approve the PR :)

2020-12-14 20:27 UTC, closed without merging