add login
Borders-None/bookshop-project-2020-autumn pull request #19
Opened 2020-12-17 19:34 UTC by pouriya91

login added

2020-12-17 20:00 UTC, josipgrgic commented on Login/login.js
> +    this.sessionStorage.setItem("password", "KEV9EwC5SEvk4dF");
We don't initialize the session storage with any values. As I said, adding login information to GitHub is a big security risk! 
Please delete these lines

2020-12-17 20:04 UTC, josipgrgic commented on Login/login.js
> +            == sessionStorage.getItem("password")))
This code is too complicated.

The flow should look like this:
- get the values from the input elements
- if the username input value **is empty** **or** the password input value **is empty** 
  - then add an error
  - return
- if the username input value **and** the password input value **are not empty**
  - store the username and password in the session storage
  - return
And that's it

2020-12-17 20:05 UTC, josipgrgic commented on Login/login.js
> +            == sessionStorage.getItem("password")))
So you don't need to compare usernames and passwords

2020-12-17 20:06 UTC, josipgrgic requested changes
Please resolve the issues I pointed out :)

2020-12-17 20:07 UTC, josipgrgic commented
You also need to add a link to the login page from the home page so that users know it exits

2020-12-21 19:06 UTC, josipgrgic requested changes
Did you notice the strange characters in your code? These appeared because your branch has merge conflicts with the main branch. When that happens, you have to resolve these conflicts and not push the conflicting changes.

I would really like to help you with this sometime tomorrow because it seems that you have a hard time with fixing everything :)

2020-12-21 19:51 UTC, pouriya91 commented
No, because me and Ahmad did it together, in my system didn't have strange characters

2020-12-22 14:24 UTC, AhmadAlkaati commented
> No, because me and Ahmad did it together, in my system didn't have strange characters

k

2020-12-22 18:14 UTC, josipgrgic commented
> > No, because me and Ahmad did it together, in my system didn't have strange characters
> > I agree with @josipgrgic about having a zoom call with him and sharing your screen so he can see what needs to be fixed now.
> > Yesterday I managed that we push your latest code to the same branch where you had your code last time but I am not sure how to solve conflicts.
> > Surely Josip knows a lot more about github :)

The issue is most surely because you didn't merge the main branch into this one in a while. We can make a call, but I was and still am busy today, so maybe tomorrow before or after the wrap-up meeting?

2020-12-27 22:34 UTC, closed without merging